CREATE TABLE MEMBER(
    ID VARCHAR2(30) PRIMARY KEY,
    PW VARCHAR2(30),
    AGE NUMBER(3),
    EMAIL VARCHAR2(30)
)
SELECT * FROM MEMBER;

INSERT INTO MEMBER VALUES('AAA', 'AAA', 10, 'AAA');
INSERT INTO MEMBER VALUES('BBB', 'BBB', 10, 'BBB');
INSERT INTO MEMBER VALUES('CCC', 'CCC', 10, 'CCC');
INSERT INTO MEMBER VALUES('DDD', 'DDD', 10, 'DDD');

COMMIT;

SELECT e.employee_id, e.job_id, d.department_name, e.first_name
FROM EMPLOYEES E
LEFT JOIN DEPARTMENTS D
ON E.department_id = d.department_id
WHERE e.employee_id = '100';